---
- name: Check if bin directory exists in home
  stat:
    path: ~/bin
  register: stat_bin_result
  tags:
    - scripts
    - minimal

- name: Copy bin scripts to home
  copy:
    src: files/bin
    dest: ~/
    mode: '0700'
    force: true
  tags:
    - scripts
    - minimal
