---
- name: Change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - shell
 
- name: Copy aliases file
  copy:
    src: files/aliases
    dest: ~/.aliases
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - shell
    - minimal

- name: Copy functions file
  copy:
    src: files/functions
    dest: ~/.functions
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - shell
    - minimal

- name: Copy variables file
  copy:
    src: files/variables
    dest: ~/.variables
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - shell
    - minimal

- name: Copy inputrc file
  copy:
    src: files/inputrc
    dest: ~/.inputrc
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - shell
    - minimal
