version: 2
jobs:
  build-remote:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install -y curl
      - run: bash -c "$(curl -fsSL https://bit.ly/dfdotfiles)" && source ~/.bashrc
  build-local:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./bin/dotfiles
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-local
      - build-remote
