# Where the magic happens.
export DOTFILES=~/.dotfiles

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

export TERM="screen-256color"

export TMUXIFIER_LAYOUT_PATH="$HOME/.dotfiles/link/tmux-layouts"

# Add binaries into the path
export PATH="$DOTFILES/bin:$HOME/.tmuxifier/bin:$PATH"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,pack,minpac,vendor,plugins}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# bind -x '"\C-p": vim $(fzf);'

# Add Dircolors
if [ -x "$(command -v dircolors)" ]; then
  eval $(dircolors "$HOME/.dotfiles/conf/dircolors.256dark")
fi

if [ -x "$(command -v direnv)" ]; then
  eval "$(direnv hook bash)"
fi

# Source all files in "completion"
function completion() {
  local file
  for file in $DOTFILES/conf/bash-completion.d/*; do
    source "$file"
  done
}

# Source all files in "source"
function src() {
  local file
  if [[ "$1" ]]; then
    source "$DOTFILES/source/$1.sh"
  else
    for file in $DOTFILES/source/*; do
      source "$file"
    done
  fi
}


completion
src
