---
- name: Install zsh shell
  ansible.builtin.package:
    name: zsh
    state: present
  tags:
    - zsh

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  tags:
    - zsh

- name: Copy zshrc file
  copy:
    src: files/zshrc
    dest: ~/.zshrc
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - zsh

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  tags:
    - zsh

- name: Cloning oh-my-zsh
  git:
    repo={{ oh_my_zsh_url }}
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - zsh

- name: Check if zsh-autosuggestions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: stat_oh_my_zsh_autosuggestions_result
  tags:
    - zsh

- name: Cloning zsh-autosuggestions
  git:
    repo={{ zsh_autosuggestions_url }}
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  when: not stat_oh_my_zsh_autosuggestions_result.stat.exists
  tags:
    - zsh

- name: Check if zsh-completions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-completions
  register: stat_oh_my_zsh_completions_result
  tags:
    - zsh

- name: Cloning zsh-completions
  git:
    repo={{ zsh_completions_url }}
    dest=~/.oh-my-zsh/custom/plugins/zsh-completions
  when: not stat_oh_my_zsh_completions_result.stat.exists
  tags:
    - zsh

# - name: "Install .zshrc from template"
#   template:
#     src: zshrc.j2
#     dest: "~/.zshrc"
#     mode: 0644
#   tags:
#     - zsh