---
- name: Install zsh shell
  ansible.builtin.package:
    name: zsh
    state: present
  tags:
    - zsh

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  tags:
    - zsh

- name: Copy zshrc file
  copy:
    src: files/zshrc
    dest: ~/.zshrc
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    backup: true
    force: true
  tags:
    - zsh
#  when: not stat_rc_result.stat.exists

# - name: Check if .oh-my-zsh exists
#   stat:
#     path: ~/.oh-my-zsh
#   register: stat_oh_my_zsh_result
#   tags:
#     - zsh

# - name: Cloning oh-my-zsh
#   git:
#     repo=https://github.com/robbyrussell/oh-my-zsh
#     dest=~/.oh-my-zsh
#   when: not stat_oh_my_zsh_result.stat.exists
#   tags:
#     - zsh

# - name: Check if zsh-autosuggestions exists
#   stat:
#     path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
#   register: stat_oh_my_zsh_autosuggestions_result
#   tags:
#     - zsh

# - name: Cloning zsh-autosuggestions
#   git:
#     repo=https://github.com/zsh-users/zsh-autosuggestions
#     dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
#   when: not stat_oh_my_zsh_autosuggestions_result.stat.exists
#   tags:
#     - zsh

# - name: "Install .zshrc from template"
#   template:
#     src: zshrc.j2
#     dest: "~/.zshrc"
#     mode: 0644
#   tags:
#     - zsh