---
# - name: Install dircolors
#   ansible.builtin.package:
#     name: dircolors
#     state: present
#   tags:
#     - dircolors

- name: Create dircolors directory
  file:
    path: ~/.config/dircolors
    state: directory
  tags:
    - dircolors
    - minimal

- name: "Copy dircolors config"
  ansible.builtin.copy:
    src: files/dircolors.256dark
    dest: "~/.config/dircolors/"
    mode: 0644
  tags:
    - dircolors
    - minimal
