---
- name: Verify
  hosts: all

  tasks:
  - name: "Stat Dotfiles Directory"
    stat: path=~/.dotfiles
    register: p
  - debug: msg="Dotfiles path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir
