---
- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present
  tags:
    - vim
    - minimal

- name: "Copy vimrc"
  ansible.builtin.copy:
    src: files/vimrc
    dest: "~/.vimrc"
    mode: 0644
  tags:
    - vim
    - minimal

- name: "Copy gvimrc"
  ansible.builtin.copy:
    src: files/gvimrc
    dest: "~/.gvimrc"
    mode: 0644
  tags:
    - vim
    - minimal

- name: Create .vim directory
  file:
    path: ~/.vim
    state: directory
  register: vimdir_result
  tags:
    - vim
    - minimal


- name: Check if minpac exists
  stat:
    path: ~/.vim/pack/minpac/opt/minpac
  register: stat_minpac_result
  tags:
    - vim
    - minimal

- name: Cloning minpac
  git:
    repo={{ minpac_url }}
    dest=~/.vim/pack/minpac/opt/minpac
  when: not stat_minpac_result.stat.exists
  tags:
    - vim
    - minimal

- name: Install Vim Plugins
  ansible.builtin.command:
    cmd: vim +PackSetup
    creates: ~/.vim/pack/minpac/start

- name: "Copy UltiSnips"
  ansible.builtin.copy:
    src: files/UltiSnips
    dest: "~/.vim/"
  tags:
    - vim
    - minimal